package co.com.interkont.wsmiobra.dto;
// Generated 26/02/2021 12:58:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name="contrato"
    ,schema="public"
)
public class Contrato  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intidcontrato;
     private Tercero terceroByIntidsupervisor;
     private Tercero terceroByFkgerenteconvenio;
     private Tercero terceroByIntentidad;
     @JsonIgnore
     private Contrato contrato;
     private String strnombre;
     @Temporal(TemporalType.DATE)
     private Date datefechaini;
     @Temporal(TemporalType.DATE)
     private Date datefechafin;
     private String strnumcontrato;
     private BigDecimal numvlrcontrato;
     private Integer intidformapago;
     @Temporal(TemporalType.DATE)
     private Date datefechacreacion;
     @Temporal(TemporalType.DATE)
     private Date datefechamodificacion;
     private BigDecimal numrecursospropios;
     private BigDecimal numrecursosch;
     private BigDecimal numrecursostercero;
     private String textobjeto;
     @Temporal(TemporalType.DATE)
     private Date datefechaultimaprorroga;
     private Integer intduraciondias;
     private Integer numcargofiduciario;
     private int inttipoestadoobra;
     private Integer inttipocontrato;
     private Integer intcodigocontratista;
     private Integer intusumodificacion;
     private int intusucreacion;
     private Integer intidtipocontratoconsultoria;
     private BigDecimal numvlrsumahijos;
     private boolean booltipocontratoconvenio;
     private boolean booleantienehijos;
     private Integer intidperiodoevento;
     private Integer intcantproyectos;
     private Integer inttipificacionadicional;
     private BigDecimal numvlrsumaproyectos;
     private Integer intidmodalidadcontratista;
     private Double valordisponible;
     private Boolean boolplanoperativo;
     private Integer fkIntestadoconvenio;
     @Temporal(TemporalType.DATE)
     private Date fechasuscripcion;
     private Double valordisponiblegerencia;
     private BigDecimal numvalorgerencia;
     @Temporal(TemporalType.DATE)
     private Date fechaactaini;
     @Temporal(TemporalType.DATE)
     private Date fecIniPrecontractual;
     private String strenlaceproceso;
     private Integer intanio;
     private String strcodigocdp;
     private String strcodigorpc;
     private Integer intidmodalidadcontrato;
     private Integer fkIntestadocontrato;
     @Temporal(TemporalType.DATE)
     private Date datefinalizacion;
     @Temporal(TemporalType.DATE)
     private Date dateliquidacion;
     private Integer lineanegocio;
     private int intmesesliquidacion;
     @Temporal(TemporalType.DATE)
     private Date datefecinicioSupervisor;
     @Temporal(TemporalType.DATE)
     private Date datefecfinSupervisor;
     @JsonIgnore
     private Set<FuenterecursosconvenioLog> fuenterecursosconvenioLogs = new HashSet<FuenterecursosconvenioLog>(0);
     @JsonIgnore
     private Set<Fuenterecursosconvenio> fuenterecursosconvenios = new HashSet<Fuenterecursosconvenio>(0);
     @JsonIgnore
     private Set<Contrato> contratos = new HashSet<Contrato>(0);

    public Contrato() {
    }

	
    public Contrato(int intidcontrato, String strnombre, BigDecimal numvlrcontrato, Date datefechacreacion, int inttipoestadoobra, int intusucreacion, BigDecimal numvlrsumahijos, boolean booltipocontratoconvenio, boolean booleantienehijos, BigDecimal numvlrsumaproyectos, int intmesesliquidacion) {
        this.intidcontrato = intidcontrato;
        this.strnombre = strnombre;
        this.numvlrcontrato = numvlrcontrato;
        this.datefechacreacion = datefechacreacion;
        this.inttipoestadoobra = inttipoestadoobra;
        this.intusucreacion = intusucreacion;
        this.numvlrsumahijos = numvlrsumahijos;
        this.booltipocontratoconvenio = booltipocontratoconvenio;
        this.booleantienehijos = booleantienehijos;
        this.numvlrsumaproyectos = numvlrsumaproyectos;
        this.intmesesliquidacion = intmesesliquidacion;
    }
    public Contrato(int intidcontrato, Tercero terceroByIntidsupervisor, Tercero terceroByFkgerenteconvenio, Tercero terceroByIntentidad, Contrato contrato, String strnombre, Date datefechaini, Date datefechafin, String strnumcontrato, BigDecimal numvlrcontrato, Integer intidformapago, Date datefechacreacion, Date datefechamodificacion, BigDecimal numrecursospropios, BigDecimal numrecursosch, BigDecimal numrecursostercero, String textobjeto, Date datefechaultimaprorroga, Integer intduraciondias, Integer numcargofiduciario, int inttipoestadoobra, Integer inttipocontrato, Integer intcodigocontratista, Integer intusumodificacion, int intusucreacion, Integer intidtipocontratoconsultoria, BigDecimal numvlrsumahijos, boolean booltipocontratoconvenio, boolean booleantienehijos, Integer intidperiodoevento, Integer intcantproyectos, Integer inttipificacionadicional, BigDecimal numvlrsumaproyectos, Integer intidmodalidadcontratista, Double valordisponible, Boolean boolplanoperativo, Integer fkIntestadoconvenio, Date fechasuscripcion, Double valordisponiblegerencia, BigDecimal numvalorgerencia, Date fechaactaini, Date fecIniPrecontractual, String strenlaceproceso, Integer intanio, String strcodigocdp, String strcodigorpc, Integer intidmodalidadcontrato, Integer fkIntestadocontrato, Date datefinalizacion, Date dateliquidacion, Integer lineanegocio, int intmesesliquidacion, Date datefecinicioSupervisor, Date datefecfinSupervisor, Set<FuenterecursosconvenioLog> fuenterecursosconvenioLogs, Set<Fuenterecursosconvenio> fuenterecursosconvenios, Set<Contrato> contratos) {
       this.intidcontrato = intidcontrato;
       this.terceroByIntidsupervisor = terceroByIntidsupervisor;
       this.terceroByFkgerenteconvenio = terceroByFkgerenteconvenio;
       this.terceroByIntentidad = terceroByIntentidad;
       this.contrato = contrato;
       this.strnombre = strnombre;
       this.datefechaini = datefechaini;
       this.datefechafin = datefechafin;
       this.strnumcontrato = strnumcontrato;
       this.numvlrcontrato = numvlrcontrato;
       this.intidformapago = intidformapago;
       this.datefechacreacion = datefechacreacion;
       this.datefechamodificacion = datefechamodificacion;
       this.numrecursospropios = numrecursospropios;
       this.numrecursosch = numrecursosch;
       this.numrecursostercero = numrecursostercero;
       this.textobjeto = textobjeto;
       this.datefechaultimaprorroga = datefechaultimaprorroga;
       this.intduraciondias = intduraciondias;
       this.numcargofiduciario = numcargofiduciario;
       this.inttipoestadoobra = inttipoestadoobra;
       this.inttipocontrato = inttipocontrato;
       this.intcodigocontratista = intcodigocontratista;
       this.intusumodificacion = intusumodificacion;
       this.intusucreacion = intusucreacion;
       this.intidtipocontratoconsultoria = intidtipocontratoconsultoria;
       this.numvlrsumahijos = numvlrsumahijos;
       this.booltipocontratoconvenio = booltipocontratoconvenio;
       this.booleantienehijos = booleantienehijos;
       this.intidperiodoevento = intidperiodoevento;
       this.intcantproyectos = intcantproyectos;
       this.inttipificacionadicional = inttipificacionadicional;
       this.numvlrsumaproyectos = numvlrsumaproyectos;
       this.intidmodalidadcontratista = intidmodalidadcontratista;
       this.valordisponible = valordisponible;
       this.boolplanoperativo = boolplanoperativo;
       this.fkIntestadoconvenio = fkIntestadoconvenio;
       this.fechasuscripcion = fechasuscripcion;
       this.valordisponiblegerencia = valordisponiblegerencia;
       this.numvalorgerencia = numvalorgerencia;
       this.fechaactaini = fechaactaini;
       this.fecIniPrecontractual = fecIniPrecontractual;
       this.strenlaceproceso = strenlaceproceso;
       this.intanio = intanio;
       this.strcodigocdp = strcodigocdp;
       this.strcodigorpc = strcodigorpc;
       this.intidmodalidadcontrato = intidmodalidadcontrato;
       this.fkIntestadocontrato = fkIntestadocontrato;
       this.datefinalizacion = datefinalizacion;
       this.dateliquidacion = dateliquidacion;
       this.lineanegocio = lineanegocio;
       this.intmesesliquidacion = intmesesliquidacion;
       this.datefecinicioSupervisor = datefecinicioSupervisor;
       this.datefecfinSupervisor = datefecfinSupervisor;
       this.fuenterecursosconvenioLogs = fuenterecursosconvenioLogs;
       this.fuenterecursosconvenios = fuenterecursosconvenios;
       this.contratos = contratos;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ContratoSequenceGenerator")
 	@SequenceGenerator(name = "ContratoSequenceGenerator", sequenceName="contrato_intidcontrato_seq")
 	@Column(name="intidcontrato", unique=true, nullable=false)
    public int getIntidcontrato() {
        return this.intidcontrato;
    }
    
    public void setIntidcontrato(int intidcontrato) {
        this.intidcontrato = intidcontrato;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="intidsupervisor")
    public Tercero getTerceroByIntidsupervisor() {
        return this.terceroByIntidsupervisor;
    }
    
    public void setTerceroByIntidsupervisor(Tercero terceroByIntidsupervisor) {
        this.terceroByIntidsupervisor = terceroByIntidsupervisor;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fkgerenteconvenio")
    public Tercero getTerceroByFkgerenteconvenio() {
        return this.terceroByFkgerenteconvenio;
    }
    
    public void setTerceroByFkgerenteconvenio(Tercero terceroByFkgerenteconvenio) {
        this.terceroByFkgerenteconvenio = terceroByFkgerenteconvenio;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="intentidad")
    public Tercero getTerceroByIntentidad() {
        return this.terceroByIntentidad;
    }
    
    public void setTerceroByIntentidad(Tercero terceroByIntentidad) {
        this.terceroByIntentidad = terceroByIntentidad;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fk_intidcontrato")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    
    @Column(name="strnombre", nullable=false)
    public String getStrnombre() {
        return this.strnombre;
    }
    
    public void setStrnombre(String strnombre) {
        this.strnombre = strnombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefechaini", length=13)
    public Date getDatefechaini() {
        return this.datefechaini;
    }
    
    public void setDatefechaini(Date datefechaini) {
        this.datefechaini = datefechaini;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefechafin", length=13)
    public Date getDatefechafin() {
        return this.datefechafin;
    }
    
    public void setDatefechafin(Date datefechafin) {
        this.datefechafin = datefechafin;
    }

    
    @Column(name="strnumcontrato")
    public String getStrnumcontrato() {
        return this.strnumcontrato;
    }
    
    public void setStrnumcontrato(String strnumcontrato) {
        this.strnumcontrato = strnumcontrato;
    }

    
    @Column(name="numvlrcontrato", nullable=false, precision=20, scale=6)
    public BigDecimal getNumvlrcontrato() {
        return this.numvlrcontrato;
    }
    
    public void setNumvlrcontrato(BigDecimal numvlrcontrato) {
        this.numvlrcontrato = numvlrcontrato;
    }

    
    @Column(name="intidformapago")
    public Integer getIntidformapago() {
        return this.intidformapago;
    }
    
    public void setIntidformapago(Integer intidformapago) {
        this.intidformapago = intidformapago;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datefechacreacion", nullable=false, length=35)
    public Date getDatefechacreacion() {
        return this.datefechacreacion;
    }
    
    public void setDatefechacreacion(Date datefechacreacion) {
        this.datefechacreacion = datefechacreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datefechamodificacion", length=35)
    public Date getDatefechamodificacion() {
        return this.datefechamodificacion;
    }
    
    public void setDatefechamodificacion(Date datefechamodificacion) {
        this.datefechamodificacion = datefechamodificacion;
    }

    
    @Column(name="numrecursospropios", precision=20, scale=6)
    public BigDecimal getNumrecursospropios() {
        return this.numrecursospropios;
    }
    
    public void setNumrecursospropios(BigDecimal numrecursospropios) {
        this.numrecursospropios = numrecursospropios;
    }

    
    @Column(name="numrecursosch", precision=20, scale=6)
    public BigDecimal getNumrecursosch() {
        return this.numrecursosch;
    }
    
    public void setNumrecursosch(BigDecimal numrecursosch) {
        this.numrecursosch = numrecursosch;
    }

    
    @Column(name="numrecursostercero", precision=20, scale=6)
    public BigDecimal getNumrecursostercero() {
        return this.numrecursostercero;
    }
    
    public void setNumrecursostercero(BigDecimal numrecursostercero) {
        this.numrecursostercero = numrecursostercero;
    }

    
    @Column(name="textobjeto")
    public String getTextobjeto() {
        return this.textobjeto;
    }
    
    public void setTextobjeto(String textobjeto) {
        this.textobjeto = textobjeto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefechaultimaprorroga", length=13)
    public Date getDatefechaultimaprorroga() {
        return this.datefechaultimaprorroga;
    }
    
    public void setDatefechaultimaprorroga(Date datefechaultimaprorroga) {
        this.datefechaultimaprorroga = datefechaultimaprorroga;
    }

    
    @Column(name="intduraciondias")
    public Integer getIntduraciondias() {
        return this.intduraciondias;
    }
    
    public void setIntduraciondias(Integer intduraciondias) {
        this.intduraciondias = intduraciondias;
    }

    
    @Column(name="numcargofiduciario")
    public Integer getNumcargofiduciario() {
        return this.numcargofiduciario;
    }
    
    public void setNumcargofiduciario(Integer numcargofiduciario) {
        this.numcargofiduciario = numcargofiduciario;
    }

    
    @Column(name="inttipoestadoobra", nullable=false)
    public int getInttipoestadoobra() {
        return this.inttipoestadoobra;
    }
    
    public void setInttipoestadoobra(int inttipoestadoobra) {
        this.inttipoestadoobra = inttipoestadoobra;
    }

    
    @Column(name="inttipocontrato")
    public Integer getInttipocontrato() {
        return this.inttipocontrato;
    }
    
    public void setInttipocontrato(Integer inttipocontrato) {
        this.inttipocontrato = inttipocontrato;
    }

    
    @Column(name="intcodigocontratista")
    public Integer getIntcodigocontratista() {
        return this.intcodigocontratista;
    }
    
    public void setIntcodigocontratista(Integer intcodigocontratista) {
        this.intcodigocontratista = intcodigocontratista;
    }

    
    @Column(name="intusumodificacion")
    public Integer getIntusumodificacion() {
        return this.intusumodificacion;
    }
    
    public void setIntusumodificacion(Integer intusumodificacion) {
        this.intusumodificacion = intusumodificacion;
    }

    
    @Column(name="intusucreacion", nullable=false)
    public int getIntusucreacion() {
        return this.intusucreacion;
    }
    
    public void setIntusucreacion(int intusucreacion) {
        this.intusucreacion = intusucreacion;
    }

    
    @Column(name="intidtipocontratoconsultoria")
    public Integer getIntidtipocontratoconsultoria() {
        return this.intidtipocontratoconsultoria;
    }
    
    public void setIntidtipocontratoconsultoria(Integer intidtipocontratoconsultoria) {
        this.intidtipocontratoconsultoria = intidtipocontratoconsultoria;
    }

    
    @Column(name="numvlrsumahijos", nullable=false, precision=20, scale=6)
    public BigDecimal getNumvlrsumahijos() {
        return this.numvlrsumahijos;
    }
    
    public void setNumvlrsumahijos(BigDecimal numvlrsumahijos) {
        this.numvlrsumahijos = numvlrsumahijos;
    }

    
    @Column(name="booltipocontratoconvenio", nullable=false)
    public boolean isBooltipocontratoconvenio() {
        return this.booltipocontratoconvenio;
    }
    
    public void setBooltipocontratoconvenio(boolean booltipocontratoconvenio) {
        this.booltipocontratoconvenio = booltipocontratoconvenio;
    }

    
    @Column(name="booleantienehijos", nullable=false)
    public boolean isBooleantienehijos() {
        return this.booleantienehijos;
    }
    
    public void setBooleantienehijos(boolean booleantienehijos) {
        this.booleantienehijos = booleantienehijos;
    }

    
    @Column(name="intidperiodoevento")
    public Integer getIntidperiodoevento() {
        return this.intidperiodoevento;
    }
    
    public void setIntidperiodoevento(Integer intidperiodoevento) {
        this.intidperiodoevento = intidperiodoevento;
    }

    
    @Column(name="intcantproyectos")
    public Integer getIntcantproyectos() {
        return this.intcantproyectos;
    }
    
    public void setIntcantproyectos(Integer intcantproyectos) {
        this.intcantproyectos = intcantproyectos;
    }

    
    @Column(name="inttipificacionadicional")
    public Integer getInttipificacionadicional() {
        return this.inttipificacionadicional;
    }
    
    public void setInttipificacionadicional(Integer inttipificacionadicional) {
        this.inttipificacionadicional = inttipificacionadicional;
    }

    
    @Column(name="numvlrsumaproyectos", nullable=false, precision=20, scale=6)
    public BigDecimal getNumvlrsumaproyectos() {
        return this.numvlrsumaproyectos;
    }
    
    public void setNumvlrsumaproyectos(BigDecimal numvlrsumaproyectos) {
        this.numvlrsumaproyectos = numvlrsumaproyectos;
    }

    
    @Column(name="intidmodalidadcontratista")
    public Integer getIntidmodalidadcontratista() {
        return this.intidmodalidadcontratista;
    }
    
    public void setIntidmodalidadcontratista(Integer intidmodalidadcontratista) {
        this.intidmodalidadcontratista = intidmodalidadcontratista;
    }

    
    @Column(name="valordisponible", precision=17, scale=17)
    public Double getValordisponible() {
        return this.valordisponible;
    }
    
    public void setValordisponible(Double valordisponible) {
        this.valordisponible = valordisponible;
    }

    
    @Column(name="boolplanoperativo")
    public Boolean getBoolplanoperativo() {
        return this.boolplanoperativo;
    }
    
    public void setBoolplanoperativo(Boolean boolplanoperativo) {
        this.boolplanoperativo = boolplanoperativo;
    }

    
    @Column(name="fk_intestadoconvenio")
    public Integer getFkIntestadoconvenio() {
        return this.fkIntestadoconvenio;
    }
    
    public void setFkIntestadoconvenio(Integer fkIntestadoconvenio) {
        this.fkIntestadoconvenio = fkIntestadoconvenio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechasuscripcion", length=13)
    public Date getFechasuscripcion() {
        return this.fechasuscripcion;
    }
    
    public void setFechasuscripcion(Date fechasuscripcion) {
        this.fechasuscripcion = fechasuscripcion;
    }

    
    @Column(name="valordisponiblegerencia", precision=17, scale=17)
    public Double getValordisponiblegerencia() {
        return this.valordisponiblegerencia;
    }
    
    public void setValordisponiblegerencia(Double valordisponiblegerencia) {
        this.valordisponiblegerencia = valordisponiblegerencia;
    }

    
    @Column(name="numvalorgerencia", precision=131089, scale=0)
    public BigDecimal getNumvalorgerencia() {
        return this.numvalorgerencia;
    }
    
    public void setNumvalorgerencia(BigDecimal numvalorgerencia) {
        this.numvalorgerencia = numvalorgerencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaactaini", length=13)
    public Date getFechaactaini() {
        return this.fechaactaini;
    }
    
    public void setFechaactaini(Date fechaactaini) {
        this.fechaactaini = fechaactaini;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fec_ini_precontractual", length=13)
    public Date getFecIniPrecontractual() {
        return this.fecIniPrecontractual;
    }
    
    public void setFecIniPrecontractual(Date fecIniPrecontractual) {
        this.fecIniPrecontractual = fecIniPrecontractual;
    }

    
    @Column(name="strenlaceproceso")
    public String getStrenlaceproceso() {
        return this.strenlaceproceso;
    }
    
    public void setStrenlaceproceso(String strenlaceproceso) {
        this.strenlaceproceso = strenlaceproceso;
    }

    
    @Column(name="intanio")
    public Integer getIntanio() {
        return this.intanio;
    }
    
    public void setIntanio(Integer intanio) {
        this.intanio = intanio;
    }

    
    @Column(name="strcodigocdp", length=100)
    public String getStrcodigocdp() {
        return this.strcodigocdp;
    }
    
    public void setStrcodigocdp(String strcodigocdp) {
        this.strcodigocdp = strcodigocdp;
    }

    
    @Column(name="strcodigorpc", length=100)
    public String getStrcodigorpc() {
        return this.strcodigorpc;
    }
    
    public void setStrcodigorpc(String strcodigorpc) {
        this.strcodigorpc = strcodigorpc;
    }

    
    @Column(name="intidmodalidadcontrato")
    public Integer getIntidmodalidadcontrato() {
        return this.intidmodalidadcontrato;
    }
    
    public void setIntidmodalidadcontrato(Integer intidmodalidadcontrato) {
        this.intidmodalidadcontrato = intidmodalidadcontrato;
    }

    
    @Column(name="fk_intestadocontrato")
    public Integer getFkIntestadocontrato() {
        return this.fkIntestadocontrato;
    }
    
    public void setFkIntestadocontrato(Integer fkIntestadocontrato) {
        this.fkIntestadocontrato = fkIntestadocontrato;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefinalizacion", length=13)
    public Date getDatefinalizacion() {
        return this.datefinalizacion;
    }
    
    public void setDatefinalizacion(Date datefinalizacion) {
        this.datefinalizacion = datefinalizacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateliquidacion", length=13)
    public Date getDateliquidacion() {
        return this.dateliquidacion;
    }
    
    public void setDateliquidacion(Date dateliquidacion) {
        this.dateliquidacion = dateliquidacion;
    }

    
    @Column(name="lineanegocio")
    public Integer getLineanegocio() {
        return this.lineanegocio;
    }
    
    public void setLineanegocio(Integer lineanegocio) {
        this.lineanegocio = lineanegocio;
    }

    
    @Column(name="intmesesliquidacion", nullable=false)
    public int getIntmesesliquidacion() {
        return this.intmesesliquidacion;
    }
    
    public void setIntmesesliquidacion(int intmesesliquidacion) {
        this.intmesesliquidacion = intmesesliquidacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefecinicio_supervisor", length=13)
    public Date getDatefecinicioSupervisor() {
        return this.datefecinicioSupervisor;
    }
    
    public void setDatefecinicioSupervisor(Date datefecinicioSupervisor) {
        this.datefecinicioSupervisor = datefecinicioSupervisor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefecfin_supervisor", length=13)
    public Date getDatefecfinSupervisor() {
        return this.datefecfinSupervisor;
    }
    
    public void setDatefecfinSupervisor(Date datefecfinSupervisor) {
        this.datefecfinSupervisor = datefecfinSupervisor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set<FuenterecursosconvenioLog> getFuenterecursosconvenioLogs() {
        return this.fuenterecursosconvenioLogs;
    }
    
    public void setFuenterecursosconvenioLogs(Set<FuenterecursosconvenioLog> fuenterecursosconvenioLogs) {
        this.fuenterecursosconvenioLogs = fuenterecursosconvenioLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set<Fuenterecursosconvenio> getFuenterecursosconvenios() {
        return this.fuenterecursosconvenios;
    }
    
    public void setFuenterecursosconvenios(Set<Fuenterecursosconvenio> fuenterecursosconvenios) {
        this.fuenterecursosconvenios = fuenterecursosconvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contrato")
    public Set<Contrato> getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set<Contrato> contratos) {
        this.contratos = contratos;
    }




}


