package co.com.interkont.wsmiobra.dto;
// Generated 26/02/2021 12:58:18 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FuenterecursosconvenioLog generated by hbm2java
 */
@Entity
@Table(name="fuenterecursosconvenio_log"
    ,schema="planoperativo"
)
public class FuenterecursosconvenioLog  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idfuenterecursosconvenio;
     private Tercero tercero;
     private Rolentidad rolentidad;
     private Contrato contrato;
     private BigDecimal valoraportado;
     private BigDecimal otrasreservas;
     private BigDecimal reservaiva;
     private BigDecimal valorcuotagerencia;
     private Integer tipoaporte;
     private BigDecimal valordisponible;
     private Integer vigencia;
     private Double porcentajegerencia;
     private String rpc;
     private String cdp;
     private Integer contratoOrigen;
     private Date logAt;

    public FuenterecursosconvenioLog() {
    }

	@Id
	//@GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idfuenterecursosconvenio", unique=true, nullable=false)
    public int getIdfuenterecursosconvenio() {
        return this.idfuenterecursosconvenio;
    }
    
    public void setIdfuenterecursosconvenio(int idfuenterecursosconvenio) {
        this.idfuenterecursosconvenio = idfuenterecursosconvenio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkentidad")
    public Tercero getTercero() {
        return this.tercero;
    }
    
    public void setTercero(Tercero tercero) {
        this.tercero = tercero;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkrolentidad")
    public Rolentidad getRolentidad() {
        return this.rolentidad;
    }
    
    public void setRolentidad(Rolentidad rolentidad) {
        this.rolentidad = rolentidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkconvenio")
    public Contrato getContrato() {
        return this.contrato;
    }
    
    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    
    @Column(name="valoraportado", precision=20, scale=6)
    public BigDecimal getValoraportado() {
        return this.valoraportado;
    }
    
    public void setValoraportado(BigDecimal valoraportado) {
        this.valoraportado = valoraportado;
    }

    
    @Column(name="otrasreservas", precision=20, scale=6)
    public BigDecimal getOtrasreservas() {
        return this.otrasreservas;
    }
    
    public void setOtrasreservas(BigDecimal otrasreservas) {
        this.otrasreservas = otrasreservas;
    }

    
    @Column(name="reservaiva", precision=20, scale=6)
    public BigDecimal getReservaiva() {
        return this.reservaiva;
    }
    
    public void setReservaiva(BigDecimal reservaiva) {
        this.reservaiva = reservaiva;
    }

    
    @Column(name="valorcuotagerencia", precision=20, scale=6)
    public BigDecimal getValorcuotagerencia() {
        return this.valorcuotagerencia;
    }
    
    public void setValorcuotagerencia(BigDecimal valorcuotagerencia) {
        this.valorcuotagerencia = valorcuotagerencia;
    }

    
    @Column(name="tipoaporte")
    public Integer getTipoaporte() {
        return this.tipoaporte;
    }
    
    public void setTipoaporte(Integer tipoaporte) {
        this.tipoaporte = tipoaporte;
    }

    
    @Column(name="valordisponible", precision=20, scale=6)
    public BigDecimal getValordisponible() {
        return this.valordisponible;
    }
    
    public void setValordisponible(BigDecimal valordisponible) {
        this.valordisponible = valordisponible;
    }

    
    @Column(name="vigencia")
    public Integer getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(Integer vigencia) {
        this.vigencia = vigencia;
    }

    
    @Column(name="porcentajegerencia", precision=17, scale=17)
    public Double getPorcentajegerencia() {
        return this.porcentajegerencia;
    }
    
    public void setPorcentajegerencia(Double porcentajegerencia) {
        this.porcentajegerencia = porcentajegerencia;
    }

    
    @Column(name="rpc", length=100)
    public String getRpc() {
        return this.rpc;
    }
    
    public void setRpc(String rpc) {
        this.rpc = rpc;
    }

    
    @Column(name="cdp", length=100)
    public String getCdp() {
        return this.cdp;
    }
    
    public void setCdp(String cdp) {
        this.cdp = cdp;
    }

    
    @Column(name="contrato_origen")
    public Integer getContratoOrigen() {
        return this.contratoOrigen;
    }
    
    public void setContratoOrigen(Integer contratoOrigen) {
        this.contratoOrigen = contratoOrigen;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="log_at", length=29)
    public Date getLogAt() {
        return this.logAt;
    }
    
    public void setLogAt(Date logAt) {
        this.logAt = logAt;
    }
}


