package co.com.interkont.wsmiobra.dto;
// Generated 26/02/2021 12:58:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Tercero generated by hbm2java
 */
@Entity
@Table(name="tercero"
    ,schema="autenticacion"
)
public class Tercero  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intcodigo;
     private String intcedula;
     private String stremail;
     private String strnombre;
     private String strapellido1;
     private String strapellido2;
     private String strtelefono1;
     private String strtelefono2;
     private String strmovil;
     @Temporal(TemporalType.DATE)
     private Date datefechanacimiento;
     private boolean boolestado;
     @Temporal(TemporalType.DATE)
     private Date dateusuariocreacion;
     private String strdireccionprincipal;
     private int intcodigotipotercero;
     private String strcodigolocalidad;
     private Integer intcargo;
     private Integer intgenero;
     private Integer intestadoCivil;
     private Integer intcodigoverificacion;
     private Integer intcodigotipoiden;
     private String strlocalidadexpdocumento;
     private String strlocalidadnacimiento;
     private String strnombrecompleto;
     private String strpaginaweb;
     private String strfoto;
     private String strtwiter;
     private String strfacebook;
     private String strcontacto;
     private Boolean boolobraslocalidad;
     private Integer intidtipoorigen;
     private Integer intsector;
     private Integer inttiposolicitante;
     private Boolean boolentidadnacional;
     private Integer depid;
     private Boolean boolcliente;
     private String strlegal;
     @JsonIgnore
     private Set<Contrato> contratosForIntidsupervisor = new HashSet<Contrato>(0);
     @JsonIgnore
     private Set<Fuenterecursosconvenio> fuenterecursosconvenios = new HashSet<Fuenterecursosconvenio>(0);
     @JsonIgnore
     private Set<FuenterecursosconvenioLog> fuenterecursosconvenioLogs = new HashSet<FuenterecursosconvenioLog>(0);
     @JsonIgnore
     private Set<Contrato> contratosForFkgerenteconvenio = new HashSet<Contrato>(0);
     @JsonIgnore
     private Set<Contrato> contratosForIntentidad = new HashSet<Contrato>(0);

    public Tercero() {
    }

	
    public Tercero(int intcodigo, String strnombre, boolean boolestado, int intcodigotipotercero) {
        this.intcodigo = intcodigo;
        this.strnombre = strnombre;
        this.boolestado = boolestado;
        this.intcodigotipotercero = intcodigotipotercero;
    }
    public Tercero(int intcodigo, String intcedula, String stremail, String strnombre, String strapellido1, String strapellido2, String strtelefono1, String strtelefono2, String strmovil, Date datefechanacimiento, boolean boolestado, Date dateusuariocreacion, String strdireccionprincipal, int intcodigotipotercero, String strcodigolocalidad, Integer intcargo, Integer intgenero, Integer intestadoCivil, Integer intcodigoverificacion, Integer intcodigotipoiden, String strlocalidadexpdocumento, String strlocalidadnacimiento, String strnombrecompleto, String strpaginaweb, String strfoto, String strtwiter, String strfacebook, String strcontacto, Boolean boolobraslocalidad, Integer intidtipoorigen, Integer intsector, Integer inttiposolicitante, Boolean boolentidadnacional, Integer depid, Boolean boolcliente, String strlegal, Set<Contrato> contratosForIntidsupervisor, Set<Fuenterecursosconvenio> fuenterecursosconvenios, Set<FuenterecursosconvenioLog> fuenterecursosconvenioLogs, Set<Contrato> contratosForFkgerenteconvenio, Set<Contrato> contratosForIntentidad) {
       this.intcodigo = intcodigo;
       this.intcedula = intcedula;
       this.stremail = stremail;
       this.strnombre = strnombre;
       this.strapellido1 = strapellido1;
       this.strapellido2 = strapellido2;
       this.strtelefono1 = strtelefono1;
       this.strtelefono2 = strtelefono2;
       this.strmovil = strmovil;
       this.datefechanacimiento = datefechanacimiento;
       this.boolestado = boolestado;
       this.dateusuariocreacion = dateusuariocreacion;
       this.strdireccionprincipal = strdireccionprincipal;
       this.intcodigotipotercero = intcodigotipotercero;
       this.strcodigolocalidad = strcodigolocalidad;
       this.intcargo = intcargo;
       this.intgenero = intgenero;
       this.intestadoCivil = intestadoCivil;
       this.intcodigoverificacion = intcodigoverificacion;
       this.intcodigotipoiden = intcodigotipoiden;
       this.strlocalidadexpdocumento = strlocalidadexpdocumento;
       this.strlocalidadnacimiento = strlocalidadnacimiento;
       this.strnombrecompleto = strnombrecompleto;
       this.strpaginaweb = strpaginaweb;
       this.strfoto = strfoto;
       this.strtwiter = strtwiter;
       this.strfacebook = strfacebook;
       this.strcontacto = strcontacto;
       this.boolobraslocalidad = boolobraslocalidad;
       this.intidtipoorigen = intidtipoorigen;
       this.intsector = intsector;
       this.inttiposolicitante = inttiposolicitante;
       this.boolentidadnacional = boolentidadnacional;
       this.depid = depid;
       this.boolcliente = boolcliente;
       this.strlegal = strlegal;
       this.contratosForIntidsupervisor = contratosForIntidsupervisor;
       this.fuenterecursosconvenios = fuenterecursosconvenios;
       this.fuenterecursosconvenioLogs = fuenterecursosconvenioLogs;
       this.contratosForFkgerenteconvenio = contratosForFkgerenteconvenio;
       this.contratosForIntentidad = contratosForIntentidad;
    }
   
     @Id 

    
    @Column(name="intcodigo", unique=true, nullable=false)
    public int getIntcodigo() {
        return this.intcodigo;
    }
    
    public void setIntcodigo(int intcodigo) {
        this.intcodigo = intcodigo;
    }

    
    @Column(name="intcedula", length=20)
    public String getIntcedula() {
        return this.intcedula;
    }
    
    public void setIntcedula(String intcedula) {
        this.intcedula = intcedula;
    }

    
    @Column(name="stremail", length=80)
    public String getStremail() {
        return this.stremail;
    }
    
    public void setStremail(String stremail) {
        this.stremail = stremail;
    }

    
    @Column(name="strnombre", nullable=false, length=250)
    public String getStrnombre() {
        return this.strnombre;
    }
    
    public void setStrnombre(String strnombre) {
        this.strnombre = strnombre;
    }

    
    @Column(name="strapellido1", length=150)
    public String getStrapellido1() {
        return this.strapellido1;
    }
    
    public void setStrapellido1(String strapellido1) {
        this.strapellido1 = strapellido1;
    }

    
    @Column(name="strapellido2")
    public String getStrapellido2() {
        return this.strapellido2;
    }
    
    public void setStrapellido2(String strapellido2) {
        this.strapellido2 = strapellido2;
    }

    
    @Column(name="strtelefono1", length=100)
    public String getStrtelefono1() {
        return this.strtelefono1;
    }
    
    public void setStrtelefono1(String strtelefono1) {
        this.strtelefono1 = strtelefono1;
    }

    
    @Column(name="strtelefono2", length=30)
    public String getStrtelefono2() {
        return this.strtelefono2;
    }
    
    public void setStrtelefono2(String strtelefono2) {
        this.strtelefono2 = strtelefono2;
    }

    
    @Column(name="strmovil", length=30)
    public String getStrmovil() {
        return this.strmovil;
    }
    
    public void setStrmovil(String strmovil) {
        this.strmovil = strmovil;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefechanacimiento", length=13)
    public Date getDatefechanacimiento() {
        return this.datefechanacimiento;
    }
    
    public void setDatefechanacimiento(Date datefechanacimiento) {
        this.datefechanacimiento = datefechanacimiento;
    }

    
    @Column(name="boolestado", nullable=false)
    public boolean isBoolestado() {
        return this.boolestado;
    }
    
    public void setBoolestado(boolean boolestado) {
        this.boolestado = boolestado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateusuariocreacion", length=35)
    public Date getDateusuariocreacion() {
        return this.dateusuariocreacion;
    }
    
    public void setDateusuariocreacion(Date dateusuariocreacion) {
        this.dateusuariocreacion = dateusuariocreacion;
    }

    
    @Column(name="strdireccionprincipal", length=80)
    public String getStrdireccionprincipal() {
        return this.strdireccionprincipal;
    }
    
    public void setStrdireccionprincipal(String strdireccionprincipal) {
        this.strdireccionprincipal = strdireccionprincipal;
    }

    
    @Column(name="intcodigotipotercero", nullable=false)
    public int getIntcodigotipotercero() {
        return this.intcodigotipotercero;
    }
    
    public void setIntcodigotipotercero(int intcodigotipotercero) {
        this.intcodigotipotercero = intcodigotipotercero;
    }

    
    @Column(name="strcodigolocalidad", length=10)
    public String getStrcodigolocalidad() {
        return this.strcodigolocalidad;
    }
    
    public void setStrcodigolocalidad(String strcodigolocalidad) {
        this.strcodigolocalidad = strcodigolocalidad;
    }

    
    @Column(name="intcargo")
    public Integer getIntcargo() {
        return this.intcargo;
    }
    
    public void setIntcargo(Integer intcargo) {
        this.intcargo = intcargo;
    }

    
    @Column(name="intgenero")
    public Integer getIntgenero() {
        return this.intgenero;
    }
    
    public void setIntgenero(Integer intgenero) {
        this.intgenero = intgenero;
    }

    
    @Column(name="intestado_civil")
    public Integer getIntestadoCivil() {
        return this.intestadoCivil;
    }
    
    public void setIntestadoCivil(Integer intestadoCivil) {
        this.intestadoCivil = intestadoCivil;
    }

    
    @Column(name="intcodigoverificacion")
    public Integer getIntcodigoverificacion() {
        return this.intcodigoverificacion;
    }
    
    public void setIntcodigoverificacion(Integer intcodigoverificacion) {
        this.intcodigoverificacion = intcodigoverificacion;
    }

    
    @Column(name="intcodigotipoiden")
    public Integer getIntcodigotipoiden() {
        return this.intcodigotipoiden;
    }
    
    public void setIntcodigotipoiden(Integer intcodigotipoiden) {
        this.intcodigotipoiden = intcodigotipoiden;
    }

    
    @Column(name="strlocalidadexpdocumento", length=10)
    public String getStrlocalidadexpdocumento() {
        return this.strlocalidadexpdocumento;
    }
    
    public void setStrlocalidadexpdocumento(String strlocalidadexpdocumento) {
        this.strlocalidadexpdocumento = strlocalidadexpdocumento;
    }

    
    @Column(name="strlocalidadnacimiento", length=10)
    public String getStrlocalidadnacimiento() {
        return this.strlocalidadnacimiento;
    }
    
    public void setStrlocalidadnacimiento(String strlocalidadnacimiento) {
        this.strlocalidadnacimiento = strlocalidadnacimiento;
    }

    
    @Column(name="strnombrecompleto")
    public String getStrnombrecompleto() {
        return this.strnombrecompleto;
    }
    
    public void setStrnombrecompleto(String strnombrecompleto) {
        this.strnombrecompleto = strnombrecompleto;
    }

    
    @Column(name="strpaginaweb")
    public String getStrpaginaweb() {
        return this.strpaginaweb;
    }
    
    public void setStrpaginaweb(String strpaginaweb) {
        this.strpaginaweb = strpaginaweb;
    }

    
    @Column(name="strfoto")
    public String getStrfoto() {
        return this.strfoto;
    }
    
    public void setStrfoto(String strfoto) {
        this.strfoto = strfoto;
    }

    
    @Column(name="strtwiter")
    public String getStrtwiter() {
        return this.strtwiter;
    }
    
    public void setStrtwiter(String strtwiter) {
        this.strtwiter = strtwiter;
    }

    
    @Column(name="strfacebook")
    public String getStrfacebook() {
        return this.strfacebook;
    }
    
    public void setStrfacebook(String strfacebook) {
        this.strfacebook = strfacebook;
    }

    
    @Column(name="strcontacto")
    public String getStrcontacto() {
        return this.strcontacto;
    }
    
    public void setStrcontacto(String strcontacto) {
        this.strcontacto = strcontacto;
    }

    
    @Column(name="boolobraslocalidad")
    public Boolean getBoolobraslocalidad() {
        return this.boolobraslocalidad;
    }
    
    public void setBoolobraslocalidad(Boolean boolobraslocalidad) {
        this.boolobraslocalidad = boolobraslocalidad;
    }

    
    @Column(name="intidtipoorigen")
    public Integer getIntidtipoorigen() {
        return this.intidtipoorigen;
    }
    
    public void setIntidtipoorigen(Integer intidtipoorigen) {
        this.intidtipoorigen = intidtipoorigen;
    }

    
    @Column(name="intsector")
    public Integer getIntsector() {
        return this.intsector;
    }
    
    public void setIntsector(Integer intsector) {
        this.intsector = intsector;
    }

    
    @Column(name="inttiposolicitante")
    public Integer getInttiposolicitante() {
        return this.inttiposolicitante;
    }
    
    public void setInttiposolicitante(Integer inttiposolicitante) {
        this.inttiposolicitante = inttiposolicitante;
    }

    
    @Column(name="boolentidadnacional")
    public Boolean getBoolentidadnacional() {
        return this.boolentidadnacional;
    }
    
    public void setBoolentidadnacional(Boolean boolentidadnacional) {
        this.boolentidadnacional = boolentidadnacional;
    }

    
    @Column(name="depid")
    public Integer getDepid() {
        return this.depid;
    }
    
    public void setDepid(Integer depid) {
        this.depid = depid;
    }

    
    @Column(name="boolcliente")
    public Boolean getBoolcliente() {
        return this.boolcliente;
    }
    
    public void setBoolcliente(Boolean boolcliente) {
        this.boolcliente = boolcliente;
    }

    
    @Column(name="strlegal")
    public String getStrlegal() {
        return this.strlegal;
    }
    
    public void setStrlegal(String strlegal) {
        this.strlegal = strlegal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="terceroByIntidsupervisor")
    public Set<Contrato> getContratosForIntidsupervisor() {
        return this.contratosForIntidsupervisor;
    }
    
    public void setContratosForIntidsupervisor(Set<Contrato> contratosForIntidsupervisor) {
        this.contratosForIntidsupervisor = contratosForIntidsupervisor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tercero")
    public Set<Fuenterecursosconvenio> getFuenterecursosconvenios() {
        return this.fuenterecursosconvenios;
    }
    
    public void setFuenterecursosconvenios(Set<Fuenterecursosconvenio> fuenterecursosconvenios) {
        this.fuenterecursosconvenios = fuenterecursosconvenios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tercero")
    public Set<FuenterecursosconvenioLog> getFuenterecursosconvenioLogs() {
        return this.fuenterecursosconvenioLogs;
    }
    
    public void setFuenterecursosconvenioLogs(Set<FuenterecursosconvenioLog> fuenterecursosconvenioLogs) {
        this.fuenterecursosconvenioLogs = fuenterecursosconvenioLogs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="terceroByFkgerenteconvenio")
    public Set<Contrato> getContratosForFkgerenteconvenio() {
        return this.contratosForFkgerenteconvenio;
    }
    
    public void setContratosForFkgerenteconvenio(Set<Contrato> contratosForFkgerenteconvenio) {
        this.contratosForFkgerenteconvenio = contratosForFkgerenteconvenio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="terceroByIntentidad")
    public Set<Contrato> getContratosForIntentidad() {
        return this.contratosForIntentidad;
    }
    
    public void setContratosForIntentidad(Set<Contrato> contratosForIntentidad) {
        this.contratosForIntentidad = contratosForIntentidad;
    }




}


