package co.com.interkont.wscobra.dto;
// Generated 6/05/2020 11:05:19 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import co.com.interkont.wscobra.auth.pojo.JsfUsuario;

/**
 * Alimentacion generated by hbm2java
 */
@Entity
@Table(name="alimentacion"
    ,schema="public"
)
public class Alimentacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long intidalimenta;
     private JsfUsuario jsfUsuarioByIntusuAlimenta;
     private Videoevolucionobra videoevolucionobra;
     private JsfUsuario jsfUsuarioByIntusuAutoriza;
     private Obra obra;
     private Imagenevolucionobra imagenevolucionobra;
     private Semaforo semaforo;
     private BigDecimal numtotalejec;
     private BigDecimal numtotalproyacu;
     private Date datefechaalimen;
     private Date datefecha;
     private String textcomentario;
     private BigDecimal numtotalejecacu;
     private int intempleosgenerados;
     private Integer numempdirectos;
     private Integer numempindirectos;
     private Integer numhabafectados;
     private String textobservaciones;
     private String textresumenavance;
     private Integer intnumvoluntarios;
     private boolean boolaplicado;
     private Date datefechaautorizacion;
     private BigDecimal numvlrejecutadoobra;
     private Boolean aprobado;
     private String comentarioSupervisor;
     private Date dateaprobacion;
     private Integer usuIdApueba;
     private Set<Alimentacioncualificacion> alimentacioncualificacions = new HashSet<Alimentacioncualificacion>(0);
     private Set<Relacionalimentacionactividad> relacionalimentacionactividads = new HashSet<Relacionalimentacionactividad>(0);
     private Set<Relacionalimentacionfactoratraso> relacionalimentacionfactoratrasos = new HashSet<Relacionalimentacionfactoratraso>(0);

    public Alimentacion() {
    }

	
    public Alimentacion(long intidalimenta, Obra obra, Semaforo semaforo, BigDecimal numtotalejec, BigDecimal numtotalproyacu, Date datefechaalimen, Date datefecha, BigDecimal numtotalejecacu, int intempleosgenerados, boolean boolaplicado) {
        this.intidalimenta = intidalimenta;
        this.obra = obra;
        this.semaforo = semaforo;
        this.numtotalejec = numtotalejec;
        this.numtotalproyacu = numtotalproyacu;
        this.datefechaalimen = datefechaalimen;
        this.datefecha = datefecha;
        this.numtotalejecacu = numtotalejecacu;
        this.intempleosgenerados = intempleosgenerados;
        this.boolaplicado = boolaplicado;
    }
    public Alimentacion(long intidalimenta, JsfUsuario jsfUsuarioByIntusuAlimenta, Videoevolucionobra videoevolucionobra, JsfUsuario jsfUsuarioByIntusuAutoriza, Obra obra, Imagenevolucionobra imagenevolucionobra, Semaforo semaforo, BigDecimal numtotalejec, BigDecimal numtotalproyacu, Date datefechaalimen, Date datefecha, String textcomentario, BigDecimal numtotalejecacu, int intempleosgenerados, Integer numempdirectos, Integer numempindirectos, Integer numhabafectados, String textobservaciones, String textresumenavance, Integer intnumvoluntarios, boolean boolaplicado, Date datefechaautorizacion, BigDecimal numvlrejecutadoobra, Boolean aprobado, String comentarioSupervisor, Date dateaprobacion, Integer usuIdApueba) {
       this.intidalimenta = intidalimenta;
       this.jsfUsuarioByIntusuAlimenta = jsfUsuarioByIntusuAlimenta;
       this.videoevolucionobra = videoevolucionobra;
       this.jsfUsuarioByIntusuAutoriza = jsfUsuarioByIntusuAutoriza;
       this.obra = obra;
       this.imagenevolucionobra = imagenevolucionobra;
       this.semaforo = semaforo;
       this.numtotalejec = numtotalejec;
       this.numtotalproyacu = numtotalproyacu;
       this.datefechaalimen = datefechaalimen;
       this.datefecha = datefecha;
       this.textcomentario = textcomentario;
       this.numtotalejecacu = numtotalejecacu;
       this.intempleosgenerados = intempleosgenerados;
       this.numempdirectos = numempdirectos;
       this.numempindirectos = numempindirectos;
       this.numhabafectados = numhabafectados;
       this.textobservaciones = textobservaciones;
       this.textresumenavance = textresumenavance;
       this.intnumvoluntarios = intnumvoluntarios;
       this.boolaplicado = boolaplicado;
       this.datefechaautorizacion = datefechaautorizacion;
       this.numvlrejecutadoobra = numvlrejecutadoobra;
       this.aprobado = aprobado;
       this.comentarioSupervisor = comentarioSupervisor;
       this.dateaprobacion = dateaprobacion;
       this.usuIdApueba = usuIdApueba;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "alimentacionSequenceGenerator")
    @SequenceGenerator(name = "alimentacionSequenceGenerator", sequenceName="public.relacionindicadordetalleobra_intid_seq")
    @Column(name="intidalimenta", unique=true, nullable=false)
    public long getIntidalimenta() {
        return this.intidalimenta;
    }
    
    public void setIntidalimenta(long intidalimenta) {
        this.intidalimenta = intidalimenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intusu_alimenta")
    public JsfUsuario getJsfUsuarioByIntusuAlimenta() {
        return this.jsfUsuarioByIntusuAlimenta;
    }
    
    public void setJsfUsuarioByIntusuAlimenta(JsfUsuario jsfUsuarioByIntusuAlimenta) {
        this.jsfUsuarioByIntusuAlimenta = jsfUsuarioByIntusuAlimenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intidvideo")
    public Videoevolucionobra getVideoevolucionobra() {
        return this.videoevolucionobra;
    }
    
    public void setVideoevolucionobra(Videoevolucionobra videoevolucionobra) {
        this.videoevolucionobra = videoevolucionobra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intusu_autoriza")
    public JsfUsuario getJsfUsuarioByIntusuAutoriza() {
        return this.jsfUsuarioByIntusuAutoriza;
    }
    
    public void setJsfUsuarioByIntusuAutoriza(JsfUsuario jsfUsuarioByIntusuAutoriza) {
        this.jsfUsuarioByIntusuAutoriza = jsfUsuarioByIntusuAutoriza;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intcodigoobra", nullable=false)
    public Obra getObra() {
        return this.obra;
    }
    
    public void setObra(Obra obra) {
        this.obra = obra;
    }

@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.ALL)
    @JoinColumn(name="intidimagen")
    public Imagenevolucionobra getImagenevolucionobra() {
        return this.imagenevolucionobra;
    }
    
    public void setImagenevolucionobra(Imagenevolucionobra imagenevolucionobra) {
        this.imagenevolucionobra = imagenevolucionobra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intidsemaforo", nullable=false)
    public Semaforo getSemaforo() {
        return this.semaforo;
    }
    
    public void setSemaforo(Semaforo semaforo) {
        this.semaforo = semaforo;
    }

    
    @Column(name="numtotalejec", nullable=false, precision=20, scale=6)
    public BigDecimal getNumtotalejec() {
        return this.numtotalejec;
    }
    
    public void setNumtotalejec(BigDecimal numtotalejec) {
        this.numtotalejec = numtotalejec;
    }

    
    @Column(name="numtotalproyacu", nullable=false, precision=20, scale=6)
    public BigDecimal getNumtotalproyacu() {
        return this.numtotalproyacu;
    }
    
    public void setNumtotalproyacu(BigDecimal numtotalproyacu) {
        this.numtotalproyacu = numtotalproyacu;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datefechaalimen", nullable=false, length=29)
    public Date getDatefechaalimen() {
        return this.datefechaalimen;
    }
    
    public void setDatefechaalimen(Date datefechaalimen) {
        this.datefechaalimen = datefechaalimen;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefecha", nullable=false, length=13)
    public Date getDatefecha() {
        return this.datefecha;
    }
    
    public void setDatefecha(Date datefecha) {
        this.datefecha = datefecha;
    }

    
    @Column(name="textcomentario")
    public String getTextcomentario() {
        return this.textcomentario;
    }
    
    public void setTextcomentario(String textcomentario) {
        this.textcomentario = textcomentario;
    }

    
    @Column(name="numtotalejecacu", nullable=false, precision=20, scale=6)
    public BigDecimal getNumtotalejecacu() {
        return this.numtotalejecacu;
    }
    
    public void setNumtotalejecacu(BigDecimal numtotalejecacu) {
        this.numtotalejecacu = numtotalejecacu;
    }

    
    @Column(name="intempleosgenerados", nullable=false)
    public int getIntempleosgenerados() {
        return this.intempleosgenerados;
    }
    
    public void setIntempleosgenerados(int intempleosgenerados) {
        this.intempleosgenerados = intempleosgenerados;
    }

    
    @Column(name="numempdirectos")
    public Integer getNumempdirectos() {
        return this.numempdirectos;
    }
    
    public void setNumempdirectos(Integer numempdirectos) {
        this.numempdirectos = numempdirectos;
    }

    
    @Column(name="numempindirectos")
    public Integer getNumempindirectos() {
        return this.numempindirectos;
    }
    
    public void setNumempindirectos(Integer numempindirectos) {
        this.numempindirectos = numempindirectos;
    }

    
    @Column(name="numhabafectados")
    public Integer getNumhabafectados() {
        return this.numhabafectados;
    }
    
    public void setNumhabafectados(Integer numhabafectados) {
        this.numhabafectados = numhabafectados;
    }

    
    @Column(name="textobservaciones")
    public String getTextobservaciones() {
        return this.textobservaciones;
    }
    
    public void setTextobservaciones(String textobservaciones) {
        this.textobservaciones = textobservaciones;
    }

    
    @Column(name="textresumenavance")
    public String getTextresumenavance() {
        return this.textresumenavance;
    }
    
    public void setTextresumenavance(String textresumenavance) {
        this.textresumenavance = textresumenavance;
    }

    
    @Column(name="intnumvoluntarios")
    public Integer getIntnumvoluntarios() {
        return this.intnumvoluntarios;
    }
    
    public void setIntnumvoluntarios(Integer intnumvoluntarios) {
        this.intnumvoluntarios = intnumvoluntarios;
    }

    
    @Column(name="boolaplicado", nullable=false)
    public boolean isBoolaplicado() {
        return this.boolaplicado;
    }
    
    public void setBoolaplicado(boolean boolaplicado) {
        this.boolaplicado = boolaplicado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefechaautorizacion", length=13)
    public Date getDatefechaautorizacion() {
        return this.datefechaautorizacion;
    }
    
    public void setDatefechaautorizacion(Date datefechaautorizacion) {
        this.datefechaautorizacion = datefechaautorizacion;
    }

    
    @Column(name="numvlrejecutadoobra", precision=20, scale=6)
    public BigDecimal getNumvlrejecutadoobra() {
        return this.numvlrejecutadoobra;
    }
    
    public void setNumvlrejecutadoobra(BigDecimal numvlrejecutadoobra) {
        this.numvlrejecutadoobra = numvlrejecutadoobra;
    }

    
    @Column(name="aprobado")
    public Boolean getAprobado() {
        return this.aprobado;
    }
    
    public void setAprobado(Boolean aprobado) {
        this.aprobado = aprobado;
    }

    
    @Column(name="comentario_supervisor")
    public String getComentarioSupervisor() {
        return this.comentarioSupervisor;
    }
    
    public void setComentarioSupervisor(String comentarioSupervisor) {
        this.comentarioSupervisor = comentarioSupervisor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateaprobacion", length=13)
    public Date getDateaprobacion() {
        return this.dateaprobacion;
    }
    
    public void setDateaprobacion(Date dateaprobacion) {
        this.dateaprobacion = dateaprobacion;
    }

    
    @Column(name="usu_id_apueba")
    public Integer getUsuIdApueba() {
        return this.usuIdApueba;
    }
    
    public void setUsuIdApueba(Integer usuIdApueba) {
        this.usuIdApueba = usuIdApueba;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="alimentacion", cascade=CascadeType.ALL)
    public Set<Alimentacioncualificacion> getAlimentacioncualificacions() {
        return this.alimentacioncualificacions;
    }
    
    public void setAlimentacioncualificacions(Set<Alimentacioncualificacion> alimentacioncualificacions) {
        this.alimentacioncualificacions = alimentacioncualificacions;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="alimentacion", cascade=CascadeType.ALL)
    public Set<Relacionalimentacionactividad> getRelacionalimentacionactividads() {
        return this.relacionalimentacionactividads;
    }
    
    public void setRelacionalimentacionactividads(Set<Relacionalimentacionactividad> relacionalimentacionactividads) {
        this.relacionalimentacionactividads = relacionalimentacionactividads;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="alimentacion", cascade=CascadeType.ALL)
    public Set<Relacionalimentacionfactoratraso> getRelacionalimentacionfactoratrasos() {
        return this.relacionalimentacionfactoratrasos;
    }
    
    public void setRelacionalimentacionfactoratrasos(Set<Relacionalimentacionfactoratraso> relacionalimentacionfactoratrasos) {
        this.relacionalimentacionfactoratrasos = relacionalimentacionfactoratrasos;
    }

}


