package co.com.interkont.wscobra.dto;
// Generated 11/05/2020 05:39:08 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Alimentacioncualificacion generated by hbm2java
 */
@Entity
@Table(name="alimentacioncualificacion"
    ,schema="public"
)
public class Alimentacioncualificacion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intidalimencualificacion;
     private Alimentacion alimentacion;
     private String strlogro;
     private String strdificultad;
     private int intidtipocualificacion;

    public Alimentacioncualificacion() {
    }

	
    public Alimentacioncualificacion(int intidalimencualificacion, Alimentacion alimentacion, int intidtipocualificacion) {
        this.intidalimencualificacion = intidalimencualificacion;
        this.alimentacion = alimentacion;
        this.intidtipocualificacion = intidtipocualificacion;
    }
    public Alimentacioncualificacion(int intidalimencualificacion, Alimentacion alimentacion, String strlogro, String strdificultad, int intidtipocualificacion) {
       this.intidalimencualificacion = intidalimencualificacion;
       this.alimentacion = alimentacion;
       this.strlogro = strlogro;
       this.strdificultad = strdificultad;
       this.intidtipocualificacion = intidtipocualificacion;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "alimentacioncualificacionSequenceGenerator")
    @SequenceGenerator(name = "alimentacioncualificacionSequenceGenerator", sequenceName="alimentacioncualificacion_intidalimencualificacion_seq")
    @Column(name="intidalimencualificacion", unique=true, nullable=false)
    public int getIntidalimencualificacion() {
        return this.intidalimencualificacion;
    }
    
    public void setIntidalimencualificacion(int intidalimencualificacion) {
        this.intidalimencualificacion = intidalimencualificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intidalimenta", nullable=false)
    public Alimentacion getAlimentacion() {
        return this.alimentacion;
    }
    
    public void setAlimentacion(Alimentacion alimentacion) {
        this.alimentacion = alimentacion;
    }

    
    @Column(name="strlogro")
    public String getStrlogro() {
        return this.strlogro;
    }
    
    public void setStrlogro(String strlogro) {
        this.strlogro = strlogro;
    }

    
    @Column(name="strdificultad")
    public String getStrdificultad() {
        return this.strdificultad;
    }
    
    public void setStrdificultad(String strdificultad) {
        this.strdificultad = strdificultad;
    }

    
    @Column(name="intidtipocualificacion", nullable=false)
    public int getIntidtipocualificacion() {
        return this.intidtipocualificacion;
    }
    
    public void setIntidtipocualificacion(int intidtipocualificacion) {
        this.intidtipocualificacion = intidtipocualificacion;
    }




}


