package co.com.interkont.wscobra.dto;
// Generated 6/05/2020 11:05:19 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import co.com.interkont.wscobra.auth.pojo.JsfUsuario;

/**
 * Imagenevolucionobra generated by hbm2java
 */
@Entity
@Table(name="imagenevolucionobra"
    ,schema="public"
)
public class Imagenevolucionobra  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intidimagen;
     private JsfUsuario jsfUsuario;
     private Obra obra;
     private String strnombre;
     private Date datefecha;
     private String strubicacion;
     private int intidtipoimagen;
     private String strnombrearchivo;
     private Boolean booleanvalla;
     private Boolean booleanactual;
     private Date datefecharegistro;
     private Set<Alimentacion> alimentacions = new HashSet<Alimentacion>(0);

    public Imagenevolucionobra() {
    }

	
    public Imagenevolucionobra(int intidimagen, Obra obra, String strnombre, Date datefecha, int intidtipoimagen) {
        this.intidimagen = intidimagen;
        this.obra = obra;
        this.strnombre = strnombre;
        this.datefecha = datefecha;
        this.intidtipoimagen = intidtipoimagen;
    }
    public Imagenevolucionobra(int intidimagen, JsfUsuario jsfUsuario, Obra obra, String strnombre, Date datefecha, String strubicacion, int intidtipoimagen, String strnombrearchivo, Boolean booleanvalla, Boolean booleanactual, Date datefecharegistro, Set<Alimentacion> alimentacions) {
       this.intidimagen = intidimagen;
       this.jsfUsuario = jsfUsuario;
       this.obra = obra;
       this.strnombre = strnombre;
       this.datefecha = datefecha;
       this.strubicacion = strubicacion;
       this.intidtipoimagen = intidtipoimagen;
       this.strnombrearchivo = strnombrearchivo;
       this.booleanvalla = booleanvalla;
       this.booleanactual = booleanactual;
       this.datefecharegistro = datefecharegistro;
       this.alimentacions = alimentacions;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="intidimagen", unique=true, nullable=false)
    public int getIntidimagen() {
        return this.intidimagen;
    }
    
    public void setIntidimagen(int intidimagen) {
        this.intidimagen = intidimagen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intusucreacion")
    public JsfUsuario getJsfUsuario() {
        return this.jsfUsuario;
    }
    
    public void setJsfUsuario(JsfUsuario jsfUsuario) {
        this.jsfUsuario = jsfUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intcodigoobra", nullable=false)
    public Obra getObra() {
        return this.obra;
    }
    
    public void setObra(Obra obra) {
        this.obra = obra;
    }

    
    @Column(name="strnombre", nullable=false)
    public String getStrnombre() {
        return this.strnombre;
    }
    
    public void setStrnombre(String strnombre) {
        this.strnombre = strnombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefecha", nullable=false, length=13)
    public Date getDatefecha() {
        return this.datefecha;
    }
    
    public void setDatefecha(Date datefecha) {
        this.datefecha = datefecha;
    }

    
    @Column(name="strubicacion")
    public String getStrubicacion() {
        return this.strubicacion;
    }
    
    public void setStrubicacion(String strubicacion) {
        this.strubicacion = strubicacion;
    }

    
    @Column(name="intidtipoimagen", nullable=false)
    public int getIntidtipoimagen() {
        return this.intidtipoimagen;
    }
    
    public void setIntidtipoimagen(int intidtipoimagen) {
        this.intidtipoimagen = intidtipoimagen;
    }

    
    @Column(name="strnombrearchivo")
    public String getStrnombrearchivo() {
        return this.strnombrearchivo;
    }
    
    public void setStrnombrearchivo(String strnombrearchivo) {
        this.strnombrearchivo = strnombrearchivo;
    }

    
    @Column(name="booleanvalla")
    public Boolean getBooleanvalla() {
        return this.booleanvalla;
    }
    
    public void setBooleanvalla(Boolean booleanvalla) {
        this.booleanvalla = booleanvalla;
    }

    
    @Column(name="booleanactual")
    public Boolean getBooleanactual() {
        return this.booleanactual;
    }
    
    public void setBooleanactual(Boolean booleanactual) {
        this.booleanactual = booleanactual;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datefecharegistro", length=29)
    public Date getDatefecharegistro() {
        return this.datefecharegistro;
    }
    
    public void setDatefecharegistro(Date datefecharegistro) {
        this.datefecharegistro = datefecharegistro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="imagenevolucionobra")
    public Set<Alimentacion> getAlimentacions() {
        return this.alimentacions;
    }
    
    public void setAlimentacions(Set<Alimentacion> alimentacions) {
        this.alimentacions = alimentacions;
    }




}


