package co.com.interkont.wscobra.dto;
// Generated 7/05/2020 03:33:23 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name="periodo"
    ,schema="public"
)
public class Periodo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intidperiodo;
     private Obra obra;
     private Date datefeciniperiodo;
     private Date datefecfinperiodo;
     private BigDecimal numvaltotplanif;
     private Integer idfilatablaalimentaciontmp;

    public Periodo() {
    }

	
    public Periodo(int intidperiodo, Obra obra, Date datefeciniperiodo, Date datefecfinperiodo) {
        this.intidperiodo = intidperiodo;
        this.obra = obra;
        this.datefeciniperiodo = datefeciniperiodo;
        this.datefecfinperiodo = datefecfinperiodo;
    }
    public Periodo(int intidperiodo, Obra obra, Date datefeciniperiodo, Date datefecfinperiodo, BigDecimal numvaltotplanif, Integer idfilatablaalimentaciontmp) {
       this.intidperiodo = intidperiodo;
       this.obra = obra;
       this.datefeciniperiodo = datefeciniperiodo;
       this.datefecfinperiodo = datefecfinperiodo;
       this.numvaltotplanif = numvaltotplanif;
       this.idfilatablaalimentaciontmp = idfilatablaalimentaciontmp;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="intidperiodo", unique=true, nullable=false)
    public int getIntidperiodo() {
        return this.intidperiodo;
    }
    
    public void setIntidperiodo(int intidperiodo) {
        this.intidperiodo = intidperiodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intcodigoobra", nullable=false)
    public Obra getObra() {
        return this.obra;
    }
    
    public void setObra(Obra obra) {
        this.obra = obra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefeciniperiodo", nullable=false, length=13)
    public Date getDatefeciniperiodo() {
        return this.datefeciniperiodo;
    }
    
    public void setDatefeciniperiodo(Date datefeciniperiodo) {
        this.datefeciniperiodo = datefeciniperiodo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefecfinperiodo", nullable=false, length=13)
    public Date getDatefecfinperiodo() {
        return this.datefecfinperiodo;
    }
    
    public void setDatefecfinperiodo(Date datefecfinperiodo) {
        this.datefecfinperiodo = datefecfinperiodo;
    }

    
    @Column(name="numvaltotplanif", precision=20, scale=6)
    public BigDecimal getNumvaltotplanif() {
        return this.numvaltotplanif;
    }
    
    public void setNumvaltotplanif(BigDecimal numvaltotplanif) {
        this.numvaltotplanif = numvaltotplanif;
    }

    
    @Column(name="idfilatablaalimentaciontmp")
    public Integer getIdfilatablaalimentaciontmp() {
        return this.idfilatablaalimentaciontmp;
    }
    
    public void setIdfilatablaalimentaciontmp(Integer idfilatablaalimentaciontmp) {
        this.idfilatablaalimentaciontmp = idfilatablaalimentaciontmp;
    }




}


