package co.com.interkont.wscobra.dto;
// Generated 6/05/2020 06:19:02 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Relacionalimentacionactividad generated by hbm2java
 */
@Entity
@Table(name="relacionalimentacionactividad"
    ,schema="public"
)
public class Relacionalimentacionactividad  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long oidnmid;
     private Alimentacion alimentacion;
     private Actividadobra actividadobra;
     private BigDecimal numvalejec;
     private String strurlfoto;
     private String strurlvideo;
     private Double floatcantejec;

    public Relacionalimentacionactividad() {
    }

	
    public Relacionalimentacionactividad(long oidnmid, Alimentacion alimentacion, Actividadobra actividadobra, BigDecimal numvalejec) {
        this.oidnmid = oidnmid;
        this.alimentacion = alimentacion;
        this.actividadobra = actividadobra;
        this.numvalejec = numvalejec;
    }
    public Relacionalimentacionactividad(long oidnmid, Alimentacion alimentacion, Actividadobra actividadobra, BigDecimal numvalejec, String strurlfoto, String strurlvideo, Double floatcantejec) {
       this.oidnmid = oidnmid;
       this.alimentacion = alimentacion;
       this.actividadobra = actividadobra;
       this.numvalejec = numvalejec;
       this.strurlfoto = strurlfoto;
       this.strurlvideo = strurlvideo;
       this.floatcantejec = floatcantejec;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="oidnmid", unique=true, nullable=false)
    public long getOidnmid() {
        return this.oidnmid;
    }
    
    public void setOidnmid(long oidnmid) {
        this.oidnmid = oidnmid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intidalimenta", nullable=false)
    public Alimentacion getAlimentacion() {
        return this.alimentacion;
    }
    
    public void setAlimentacion(Alimentacion alimentacion) {
        this.alimentacion = alimentacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="oidactiviobra", nullable=false)
    public Actividadobra getActividadobra() {
        return this.actividadobra;
    }
    
    public void setActividadobra(Actividadobra actividadobra) {
        this.actividadobra = actividadobra;
    }

    
    @Column(name="numvalejec", nullable=false, precision=20, scale=6)
    public BigDecimal getNumvalejec() {
        return this.numvalejec;
    }
    
    public void setNumvalejec(BigDecimal numvalejec) {
        this.numvalejec = numvalejec;
    }

    
    @Column(name="strurlfoto")
    public String getStrurlfoto() {
        return this.strurlfoto;
    }
    
    public void setStrurlfoto(String strurlfoto) {
        this.strurlfoto = strurlfoto;
    }

    
    @Column(name="strurlvideo")
    public String getStrurlvideo() {
        return this.strurlvideo;
    }
    
    public void setStrurlvideo(String strurlvideo) {
        this.strurlvideo = strurlvideo;
    }

    
    @Column(name="floatcantejec", precision=17, scale=17)
    public Double getFloatcantejec() {
        return this.floatcantejec;
    }
    
    public void setFloatcantejec(Double floatcantejec) {
        this.floatcantejec = floatcantejec;
    }




}


