package co.com.interkont.wscobra.dto;
// Generated 11/05/2020 06:12:49 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Relacionindicadordetalleobra generated by hbm2java
 */
@Entity
@Table(name="relacionindicadordetalleobra"
    ,schema="public"
)
public class Relacionindicadordetalleobra  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intid;
     private Obra obra;
     private int intidindicadortipodet;
     private BigDecimal strvalor;
     private BigDecimal strvalorejecutado;
     private String strdescvalor;
     private String strdescvalorejecutado;

    public Relacionindicadordetalleobra() {
    }

	
    public Relacionindicadordetalleobra(int intid, Obra obra, int intidindicadortipodet, BigDecimal strvalor) {
        this.intid = intid;
        this.obra = obra;
        this.intidindicadortipodet = intidindicadortipodet;
        this.strvalor = strvalor;
    }
    public Relacionindicadordetalleobra(int intid, Obra obra, int intidindicadortipodet, BigDecimal strvalor, BigDecimal strvalorejecutado, String strdescvalor, String strdescvalorejecutado) {
       this.intid = intid;
       this.obra = obra;
       this.intidindicadortipodet = intidindicadortipodet;
       this.strvalor = strvalor;
       this.strvalorejecutado = strvalorejecutado;
       this.strdescvalor = strdescvalor;
       this.strdescvalorejecutado = strdescvalorejecutado;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "relacionindicadordetalleobraSequenceGenerator")
    @SequenceGenerator(name = "relacionindicadordetalleobraSequenceGenerator", sequenceName="alimentacion_intidalimenta_seq")
    @Column(name="intid", unique=true, nullable=false)
    public int getIntid() {
        return this.intid;
    }
    
    public void setIntid(int intid) {
        this.intid = intid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intcodigoobra", nullable=false)
    public Obra getObra() {
        return this.obra;
    }
    
    public void setObra(Obra obra) {
        this.obra = obra;
    }

    
    @Column(name="intidindicadortipodet", nullable=false)
    public int getIntidindicadortipodet() {
        return this.intidindicadortipodet;
    }
    
    public void setIntidindicadortipodet(int intidindicadortipodet) {
        this.intidindicadortipodet = intidindicadortipodet;
    }

    
    @Column(name="strvalor", nullable=false, precision=20, scale=6)
    public BigDecimal getStrvalor() {
        return this.strvalor;
    }
    
    public void setStrvalor(BigDecimal strvalor) {
        this.strvalor = strvalor;
    }

    
    @Column(name="strvalorejecutado", precision=20, scale=6)
    public BigDecimal getStrvalorejecutado() {
        return this.strvalorejecutado;
    }
    
    public void setStrvalorejecutado(BigDecimal strvalorejecutado) {
        this.strvalorejecutado = strvalorejecutado;
    }

    
    @Column(name="strdescvalor", length=300)
    public String getStrdescvalor() {
        return this.strdescvalor;
    }
    
    public void setStrdescvalor(String strdescvalor) {
        this.strdescvalor = strdescvalor;
    }

    
    @Column(name="strdescvalorejecutado", length=300)
    public String getStrdescvalorejecutado() {
        return this.strdescvalorejecutado;
    }
    
    public void setStrdescvalorejecutado(String strdescvalorejecutado) {
        this.strdescvalorejecutado = strdescvalorejecutado;
    }




}


