package co.com.interkont.wscobra.dto;
// Generated 6/05/2020 11:05:19 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semaforo generated by hbm2java
 */
@Entity
@Table(name="semaforo"
    ,schema="public"
)
public class Semaforo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intidsemaforo;
     private int intporini;
     private int intporfin;
     private String strimagen;
     private boolean booleanatraso;
     private int intidalarma;
     private Set<Alimentacion> alimentacions = new HashSet<Alimentacion>(0);

    public Semaforo() {
    }
    
    public Semaforo(int intidsemaforo) {
		super();
		this.intidsemaforo = intidsemaforo;
	}




	public Semaforo(int intidsemaforo, int intporini, int intporfin, String strimagen, boolean booleanatraso, int intidalarma) {
        this.intidsemaforo = intidsemaforo;
        this.intporini = intporini;
        this.intporfin = intporfin;
        this.strimagen = strimagen;
        this.booleanatraso = booleanatraso;
        this.intidalarma = intidalarma;
    }
    public Semaforo(int intidsemaforo, int intporini, int intporfin, String strimagen, boolean booleanatraso, int intidalarma, Set<Alimentacion> alimentacions) {
       this.intidsemaforo = intidsemaforo;
       this.intporini = intporini;
       this.intporfin = intporfin;
       this.strimagen = strimagen;
       this.booleanatraso = booleanatraso;
       this.intidalarma = intidalarma;
       this.alimentacions = alimentacions;
    }
   
     @Id 

    
    @Column(name="intidsemaforo", unique=true, nullable=false)
    public int getIntidsemaforo() {
        return this.intidsemaforo;
    }
    
    public void setIntidsemaforo(int intidsemaforo) {
        this.intidsemaforo = intidsemaforo;
    }

    
    @Column(name="intporini", nullable=false)
    public int getIntporini() {
        return this.intporini;
    }
    
    public void setIntporini(int intporini) {
        this.intporini = intporini;
    }

    
    @Column(name="intporfin", nullable=false)
    public int getIntporfin() {
        return this.intporfin;
    }
    
    public void setIntporfin(int intporfin) {
        this.intporfin = intporfin;
    }

    
    @Column(name="strimagen", nullable=false, length=250)
    public String getStrimagen() {
        return this.strimagen;
    }
    
    public void setStrimagen(String strimagen) {
        this.strimagen = strimagen;
    }

    
    @Column(name="booleanatraso", nullable=false)
    public boolean isBooleanatraso() {
        return this.booleanatraso;
    }
    
    public void setBooleanatraso(boolean booleanatraso) {
        this.booleanatraso = booleanatraso;
    }

    
    @Column(name="intidalarma", nullable=false)
    public int getIntidalarma() {
        return this.intidalarma;
    }
    
    public void setIntidalarma(int intidalarma) {
        this.intidalarma = intidalarma;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semaforo")
    public Set<Alimentacion> getAlimentacions() {
        return this.alimentacions;
    }
    
    public void setAlimentacions(Set<Alimentacion> alimentacions) {
        this.alimentacions = alimentacions;
    }




}


