package co.com.interkont.wscobra.dto;
// Generated 6/05/2020 11:05:19 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Videoevolucionobra generated by hbm2java
 */
@Entity
@Table(name="videoevolucionobra"
    ,schema="public"
)
public class Videoevolucionobra  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int intidvideo;
     private Obra obra;
     private String strnombre;
     private Date datefecha;
     private String strubicacion;
     private String strurlvideo;
     private boolean boolubicacionlocal;
     private Set<Alimentacion> alimentacions = new HashSet<Alimentacion>(0);

    public Videoevolucionobra() {
    }

	
    public Videoevolucionobra(int intidvideo, Obra obra, String strnombre, Date datefecha, boolean boolubicacionlocal) {
        this.intidvideo = intidvideo;
        this.obra = obra;
        this.strnombre = strnombre;
        this.datefecha = datefecha;
        this.boolubicacionlocal = boolubicacionlocal;
    }
    public Videoevolucionobra(int intidvideo, Obra obra, String strnombre, Date datefecha, String strubicacion, String strurlvideo, boolean boolubicacionlocal, Set<Alimentacion> alimentacions) {
       this.intidvideo = intidvideo;
       this.obra = obra;
       this.strnombre = strnombre;
       this.datefecha = datefecha;
       this.strubicacion = strubicacion;
       this.strurlvideo = strurlvideo;
       this.boolubicacionlocal = boolubicacionlocal;
       this.alimentacions = alimentacions;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="intidvideo", unique=true, nullable=false)
    public int getIntidvideo() {
        return this.intidvideo;
    }
    
    public void setIntidvideo(int intidvideo) {
        this.intidvideo = intidvideo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="intcodigoobra", nullable=false)
    public Obra getObra() {
        return this.obra;
    }
    
    public void setObra(Obra obra) {
        this.obra = obra;
    }

    
    @Column(name="strnombre", nullable=false)
    public String getStrnombre() {
        return this.strnombre;
    }
    
    public void setStrnombre(String strnombre) {
        this.strnombre = strnombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datefecha", nullable=false, length=13)
    public Date getDatefecha() {
        return this.datefecha;
    }
    
    public void setDatefecha(Date datefecha) {
        this.datefecha = datefecha;
    }

    
    @Column(name="strubicacion")
    public String getStrubicacion() {
        return this.strubicacion;
    }
    
    public void setStrubicacion(String strubicacion) {
        this.strubicacion = strubicacion;
    }

    
    @Column(name="strurlvideo")
    public String getStrurlvideo() {
        return this.strurlvideo;
    }
    
    public void setStrurlvideo(String strurlvideo) {
        this.strurlvideo = strurlvideo;
    }

    
    @Column(name="boolubicacionlocal", nullable=false)
    public boolean isBoolubicacionlocal() {
        return this.boolubicacionlocal;
    }
    
    public void setBoolubicacionlocal(boolean boolubicacionlocal) {
        this.boolubicacionlocal = boolubicacionlocal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="videoevolucionobra")
    public Set<Alimentacion> getAlimentacions() {
        return this.alimentacions;
    }
    
    public void setAlimentacions(Set<Alimentacion> alimentacions) {
        this.alimentacions = alimentacions;
    }




}


